# Generated by Django 3.0.7 on 2020-09-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
